config/routes.rb
Rails.application.routes.draw do
  resources :inverters
  resources :inverter_logs do
    collection { post :import }
  end
  get 'home/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inverter.rb
class Inverter < ApplicationRecord
end

app/models/inverter_log.rb
class InverterLog < ApplicationRecord
    def self.import(file)
        CSV.foreach(file.path, headers: true) do |row|
            mappings = { "identifier" => "inverter_identifier", "datetime" => "log_datetime", "energy" => "energy" }
            inverterLogRawData = row.to_hash.transform_keys(&mappings.method(:[]))
            inverterLogRawData['log_datetime'] = Time.strptime(inverterLogRawData['log_datetime'], '%m/%d/%y %R')
            InverterLog.create! inverterLogRawData
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @chart = LazyHighCharts::HighChart.new('graph') do |f|
      f.chart({zoomType: "x"})
      f.title({text: "Energy production"})
      f.subtitle({text: "Click and drag to zoom in, click legend to show/hide"})
      f.yAxis({
        title: {
          text: "Energy"
        }
      })
      f.xAxis({
        type: "datetime",
        dateTimeLabelFormats: {
          millisecond: '%H:%M',
          second: '%H:%M',
          minute: '%H:%M',
          hour: '%H:%M',
          day: '%e. %b',
          week: '%e. %b',
          month: '%b \'%y',
          year: '%Y'
        }      
      })

      # Splines for each inverter
      Inverter.all.each do |inverter|
        f.series(:type=> 'spline',:name=> "Inverter #{inverter.identifier}",:data=> InverterLog.where(inverter_identifier: inverter.id).pluck(:log_datetime, :energy))
      end
      
      # Spline for all inverters (sum of energies)
      inverterLogsWithEnergySumByDatetime = {}
      InverterLog.all.each do |inverterLog|
        if inverterLogsWithEnergySumByDatetime.key?(inverterLog.log_datetime)
          inverterLogsWithEnergySumByDatetime[inverterLog.log_datetime] += inverterLog.energy
        else
          inverterLogsWithEnergySumByDatetime[inverterLog.log_datetime] = inverterLog.energy
        end
      end
      energySumData = inverterLogsWithEnergySumByDatetime.map{|key, value| [key, value]}
      f.series(:type=> 'spline',:name=> "All inverters (sum)",:data=> energySumData)

      # Building Spline for all inverters (cumulative sums by day)
      days = energySumData.map{|datum| datum[0].to_date}.uniq
      energySumCumulativeByDayData = []
      days.each do |day|
        energySumCumulativeByDayData += helpers.cumulative_sum(energySumData.select{|datum| datum[0].to_date==day})
      end
      f.series(:type=> 'spline',:name=> "All inverters (cumulative sums by day)",:data=> energySumCumulativeByDayData)
    end
  end
end

app/controllers/inverter_logs_controller.rb
class InverterLogsController < ApplicationController
  before_action :set_inverter_log, only: [:show, :edit, :update, :destroy]

  # GET /inverter_logs
  # GET /inverter_logs.json
  def index
    @inverter_logs = InverterLog.all
  end

  # GET /inverter_logs/1
  # GET /inverter_logs/1.json
  def show
  end

  # GET /inverter_logs/new
  def new
    @inverter_log = InverterLog.new
  end

  # GET /inverter_logs/1/edit
  def edit
  end

  # POST /inverter_logs
  # POST /inverter_logs.json
  def create
    @inverter_log = InverterLog.new(inverter_log_params)

    respond_to do |format|
      if @inverter_log.save
        format.html { redirect_to @inverter_log, notice: 'Inverter log was successfully created.' }
        format.json { render :show, status: :created, location: @inverter_log }
      else
        format.html { render :new }
        format.json { render json: @inverter_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inverter_logs/1
  # PATCH/PUT /inverter_logs/1.json
  def update
    respond_to do |format|
      if @inverter_log.update(inverter_log_params)
        format.html { redirect_to @inverter_log, notice: 'Inverter log was successfully updated.' }
        format.json { render :show, status: :ok, location: @inverter_log }
      else
        format.html { render :edit }
        format.json { render json: @inverter_log.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    InverterLog.import(params[:file])
    redirect_to inverter_logs_path, notice: "Inverter Logs added"
  end

  # DELETE /inverter_logs/1
  # DELETE /inverter_logs/1.json
  def destroy
    @inverter_log.destroy
    respond_to do |format|
      format.html { redirect_to inverter_logs_url, notice: 'Inverter log was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inverter_log
      @inverter_log = InverterLog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inverter_log_params
      params.require(:inverter_log).permit(:inverter_identifier, :log_datetime, :energy)
    end
end

app/controllers/inverters_controller.rb
class InvertersController < ApplicationController
  before_action :set_inverter, only: [:show, :edit, :update, :destroy]

  # GET /inverters
  # GET /inverters.json
  def index
    @inverters = Inverter.all
  end

  # GET /inverters/1
  # GET /inverters/1.json
  def show
  end

  # GET /inverters/new
  def new
    @inverter = Inverter.new
  end

  # GET /inverters/1/edit
  def edit
  end

  # POST /inverters
  # POST /inverters.json
  def create
    @inverter = Inverter.new(inverter_params)

    respond_to do |format|
      if @inverter.save
        format.html { redirect_to @inverter, notice: 'Inverter was successfully created.' }
        format.json { render :show, status: :created, location: @inverter }
      else
        format.html { render :new }
        format.json { render json: @inverter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inverters/1
  # PATCH/PUT /inverters/1.json
  def update
    respond_to do |format|
      if @inverter.update(inverter_params)
        format.html { redirect_to @inverter, notice: 'Inverter was successfully updated.' }
        format.json { render :show, status: :ok, location: @inverter }
      else
        format.html { render :edit }
        format.json { render json: @inverter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inverters/1
  # DELETE /inverters/1.json
  def destroy
    @inverter.destroy
    respond_to do |format|
      format.html { redirect_to inverters_url, notice: 'Inverter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inverter
      @inverter = Inverter.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inverter_params
      params.require(:inverter).permit(:identifier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
    def cumulative_sum(array)
        sum = 0
        array.map{|data| [data[0], sum += data[1]]}
      end
end

app/helpers/inverter_logs_helper.rb
module InverterLogsHelper
end

app/helpers/inverters_helper.rb
module InvertersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<%= high_chart("chart_container", @chart) %>
<%= link_to "Edit/Import Logs", "/inverter_logs" %>
<%= link_to "Edit Inverters", "/inverters" %>

app/views/inverter_logs/_form.html.erb
<%= form_with(model: inverter_log, local: true) do |form| %>
  <% if inverter_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inverter_log.errors.count, "error") %> prohibited this inverter_log from being saved:</h2>

      <ul>
      <% inverter_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :inverter_identifier %>
    <%= form.number_field :inverter_identifier %>
  </div>

  <div class="field">
    <%= form.label :log_datetime %>
    <%= form.datetime_select :log_datetime %>
  </div>

  <div class="field">
    <%= form.label :energy %>
    <%= form.number_field :energy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inverter_logs/edit.html.erb
<h1>Editing Inverter Log</h1>

<%= render 'form', inverter_log: @inverter_log %>

<%= link_to 'Show', @inverter_log %> |
<%= link_to 'Back', inverter_logs_path %>

app/views/inverter_logs/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', '/' %>

<h1>Inverter Logs</h1>

<h3>Create an InverterLog</h3>
<%= link_to 'New Inverter Log', new_inverter_log_path %>

<h3>Import InverterLogs</h3>
<%= form_tag import_inverter_logs_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload Inverter Logs" %>
<% end %>


<h3>InverterLogs List</h3>
<table>
  <thead>
    <tr>
      <th>Inverter Identifier</th>
      <th>Log Datetime</th>
      <th>Energy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inverter_logs.each do |inverter_log| %>
      <tr>
        <td><%= inverter_log.inverter_identifier %></td>
        <td><%= inverter_log.log_datetime %></td>
        <td><%= inverter_log.energy %></td>
        <td><%= link_to 'Show', inverter_log %></td>
        <td><%= link_to 'Edit', edit_inverter_log_path(inverter_log) %></td>
        <td><%= link_to 'Destroy', inverter_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/inverter_logs/new.html.erb
<h1>New Inverter Log</h1>

<%= render 'form', inverter_log: @inverter_log %>

<%= link_to 'Back', inverter_logs_path %>

app/views/inverter_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Inverter Identifier:</strong>
  <%= @inverter_log.inverter_identifier %>
</p>

<p>
  <strong>Log Datetime:</strong>
  <%= @inverter_log.log_datetime %>
</p>

<p>
  <strong>Energy:</strong>
  <%= @inverter_log.energy %>
</p>

<%= link_to 'Edit', edit_inverter_log_path(@inverter_log) %> |
<%= link_to 'Back', inverter_logs_path %>

app/views/inverters/_form.html.erb
<%= form_with(model: inverter, local: true) do |form| %>
  <% if inverter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(inverter.errors.count, "error") %> prohibited this inverter from being saved:</h2>

      <ul>
      <% inverter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :identifier %>
    <%= form.number_field :identifier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/inverters/edit.html.erb
<h1>Editing Inverter</h1>

<%= render 'form', inverter: @inverter %>

<%= link_to 'Show', @inverter %> |
<%= link_to 'Back', inverters_path %>

app/views/inverters/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', '/' %>

<h1>Inverters</h1>

<table>
  <thead>
    <tr>
      <th>Identifier</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inverters.each do |inverter| %>
      <tr>
        <td><%= inverter.identifier %></td>
        <td><%= link_to 'Show', inverter %></td>
        <td><%= link_to 'Edit', edit_inverter_path(inverter) %></td>
        <td><%= link_to 'Destroy', inverter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inverter', new_inverter_path %>

app/views/inverters/new.html.erb
<h1>New Inverter</h1>

<%= render 'form', inverter: @inverter %>

<%= link_to 'Back', inverters_path %>

app/views/inverters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Identifier:</strong>
  <%= @inverter.identifier %>
</p>

<%= link_to 'Edit', edit_inverter_path(@inverter) %> |
<%= link_to 'Back', inverters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>